DPTS-19 Implement iam roles for pods
nhsd-exeter/dos-capacity-status-api pull request #114
Opened 2021-06-03 14:46 UTC by jope1

Terraformed service IAM role and attached a "dummy" policy. 
Configured K8s deployment files to use the IAM service role.

2021-06-03 14:59 UTC, dehe1 requested changes
Just a quick refactor, you're using the eks stack in the k8s account, not the eks mgmt stack in the mgmt account, so a little more readable to edit it back to "eks" not "eks_mgmt"

2021-06-03 14:59 UTC, dehe1 commented on build/automation/var/platform-texas/platform-texas-v1.mk
> +TF_VAR_eks_mgmt_terraform_state_key = eks/terraform.tfstate
Being pedantic but probably should be named "eks" not "eks_mgmt"

2021-06-03 14:59 UTC, dehe1 commented on infrastructure/stacks/service/iam.tf
> +data "terraform_remote_state" "eks-mgmt" {
Same here

2021-06-03 14:59 UTC, dehe1 commented on infrastructure/stacks/service/variables.tf
> +variable "eks_mgmt_terraform_state_key" {
and here

2021-06-07 09:01 UTC, dehe1 approved these changes
All good, thanks

2021-06-07 10:12 UTC, timrickwood approved these changes

2021-06-09 09:25 UTC, timrickwood submitted a review, later dismissed

2021-06-09 10:54 UTC, timrickwood approved these changes

2021-06-09 10:57 UTC, tamaragoldschmidt approved these changes

2021-06-09 11:00 UTC, merged